version: '3.3'
services:
  web:
    image: qsldockerhub/nginx:latest
    container_name: nginxContainer
    volumes:
      - ${NGINX_DIR}/nginx.conf:${CONTAINER_NGINX_DIR}/nginx.conf
      - ${NGINX_DIR}/vhosts:${CONTAINER_NGINX_DIR}/vhosts
      - ${NGINX_DIR}/logs:${CONTAINER_NGINX_DIR}/logs
      - ${CODE_DIR}:/home/work
    ports:
      - 80:80
      - 4586:4586
    networks:
      - program
  php:
    image: qsldockerhub/php:7.2-fpm
    container_name: phpContainer
    volumes:
     - ${PHP_DIR}/php.ini:${CONTAINER_PHP_DIR}/php.ini
     - ${PHPFPM_DIR}/php-fpm.conf:${CONTAINER_PHPFPM_DIR}/php-fpm.conf
     - ${PHPFPM_DIR}/www.conf:${CONTAINER_PHPFPM_DIR}/php-fpm.d/www.conf
     - ${CODE_DIR}:/home/work
    ports:
      - 9000:9000
      #- 20010:10010
    restart: always
    stdin_open: true
    tty: true
    networks:
      - program
  redis:
    image: redis:5
    container_name: redisContainer
    command: redis-server ${CONTAINER_REDIS_DIR}/redis.conf
    volumes:
      - ${REDIS_DIR}/redis.conf:${CONTAINER_REDIS_DIR}/redis.conf
      - ${REDIS_DIR}/dump.rdb:${CONTAINER_REDIS_DIR}/dump.rdb
    ports:
      - 6379:6379
    networks:
      - program
networks:
  program:
    driver: bridge


        #ipam:
      #driver: bridge
      #config:
        #- subnet: "172.21.0.0/24"
        #- gateway: 172.21.0.1

# docker exec -it nginx_php_new_php_1 bash